# Generated by Django 5.1.7 on 2025-03-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pdf_contrats/'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='motivation_letter',
            field=models.FileField(blank=True, null=True, upload_to='pdf_contrats/'),
        ),
    ]
