# Generated by Django 5.1.7 on 2025-03-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_cv_joboffer_motivation_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(choices=[('soins_generaux', 'Soins généraux / Cuidados gerais'), ('anesthesie', 'Infirmier anesthésiste / Enfermeiro anestesista'), ('soins_intensifs', 'Soins intensifs / Cuidados intensivos'), ('pediatrique', 'Pédiatrique / Pediátrico'), ('sante_mentale', 'Santé mentale / Saúde mental'), ('geriatrie', 'Gériatrie / Geriatria'), ('oncologie', 'Oncologie / Oncologia'), ('cardiologie', 'Cardiologie / Cardiologia'), ('soins_palliatifs', 'Soins palliatifs / Cuidados paliativos'), ('chirurgie', 'Chirurgie / Cirurgia'), ('obstetrique', 'Obstétrique / Obstetrícia'), ('neonatalogie', 'Néonatalogie / Neonatologia'), ('soins_communautaires', 'Soins communautaires / Cuidados comunitários'), ('pratique_avancee', 'Pratique avancée / Prática avançada'), ('education_sante', 'Éducation à la santé / Educação em saúde')], max_length=255),
        ),
    ]
