# Generated by Django 5.1.7 on 2025-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_specialty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joboffer',
            name='motivation_letter',
        ),
        migrations.AddField(
            model_name='application',
            name='motivation_letter',
            field=models.FileField(blank=True, null=True, upload_to='pdf_contrats/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español'), ('ro', 'Română')], default='fr', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialty',
            field=models.CharField(choices=[('soins_generaux', 'Soins généraux / General Care / Cuidados gerais / Îngrijiri generale'), ('anesthesie', 'Infirmier anesthésiste / Nurse Anesthetist / Enfermeiro anestesista / Asistent anestezist'), ('soins_intensifs', 'Soins intensifs / Intensive Care / Cuidados intensivos / Îngrijiri intensive'), ('pediatrique', 'Pédiatrique / Pediatric / Pediátrico / Pediatric'), ('sante_mentale', 'Santé mentale / Mental Health / Saúde mental / Sănătate mintală'), ('geriatrie', 'Gériatrie / Geriatrics / Geriatria / Geriatrie'), ('oncologie', 'Oncologie / Oncology / Oncologia / Oncologie'), ('cardiologie', 'Cardiologie / Cardiology / Cardiologia / Cardiologie'), ('soins_palliatifs', 'Soins palliatifs / Palliative Care / Cuidados paliativos / Îngrijiri paliative'), ('chirurgie', 'Chirurgie / Surgery / Cirurgia / Chirurgie'), ('obstetrique', 'Obstétrique / Obstetrics / Obstetrícia / Obstetrică'), ('neonatalogie', 'Néonatalogie / Neonatology / Neonatologia / Neonatologie'), ('soins_communautaires', 'Soins communautaires / Community Care / Cuidados comunitários / Îngrijiri comunitare'), ('pratique_avancee', 'Pratique avancée / Advanced Practice / Prática avançada / Practică avansată'), ('education_sante', 'Éducation à la santé / Health Education / Educação em saúde / Educație pentru sănătate')], max_length=255),
        ),
    ]
