# Generated by Django 5.1.7 on 2025-03-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.DeleteModel(
            name='Recruiter',
        ),
    ]
